language: julia
os:
    - linux
julia:
    - 0.5
    - nightly
notifications:
    email: false
sudo: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.test("YAML", coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("YAML")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
